// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Hb9P4vCx2UnATTI2gD9hcZe0SG7Phlo',
    appId: '1:741134073278:web:1ca645a04598f565d78def',
    messagingSenderId: '741134073278',
    projectId: 'smuvix-622a7',
    authDomain: 'smuvix-622a7.firebaseapp.com',
    storageBucket: 'smuvix-622a7.firebasestorage.app',
    measurementId: 'G-QE85CL549H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO22FuTLosKr5waoJB92OsjEyqXOrcXU8',
    appId: '1:741134073278:android:15f0411dc25531a6d78def',
    messagingSenderId: '741134073278',
    projectId: 'smuvix-622a7',
    storageBucket: 'smuvix-622a7.firebasestorage.app',
  );
}
