const Map<String, ({String name, String symbol})> kCurrencies = {
  'AED': (name: 'United Arab Emirates dirham', symbol: 'د.إ'),
  'AFN': (name: 'Afghan afghani', symbol: '؋'),
  'ALL': (name: 'Albanian lek', symbol: 'L'),
  'AMD': (name: 'Armenian dram', symbol: '֏'),
  'ANG': (name: 'Netherlands Antillean guilder', symbol: 'ƒ'),
  'AOA': (name: 'Angolan kwanza', symbol: 'Kz'),
  'ARS': (name: 'Argentine peso', symbol: '\$'),
  'AUD': (name: 'Australian dollar', symbol: '\$'),
  'AWG': (name: 'Aruban florin', symbol: 'ƒ'),
  'AZN': (name: 'Azerbaijani manat', symbol: '₼'),
  'BAM': (name: 'Bosnia and Herzegovina convertible mark', symbol: 'KM'),
  'BBD': (name: 'Barbadian dollar', symbol: '\$'),
  'BDT': (name: 'Bangladeshi taka', symbol: '৳'),
  'BGN': (name: 'Bulgarian lev', symbol: 'лв'),
  'BHD': (name: 'Bahraini dinar', symbol: '.د.ب'),
  'BIF': (name: 'Burundian franc', symbol: 'Fr'),
  'BMD': (name: 'Bermudian dollar', symbol: '\$'),
  'BND': (name: 'Brunei dollar', symbol: '\$'),
  'BOB': (name: 'Bolivian boliviano', symbol: 'Bs.'),
  'BRL': (name: 'Brazilian real', symbol: 'R\$'),
  'BSD': (name: 'Bahamian dollar', symbol: '\$'),
  'BTN': (name: 'Bhutanese ngultrum', symbol: 'Nu.'),
  'BWP': (name: 'Botswana pula', symbol: 'P'),
  'BYN': (name: 'Belarusian ruble', symbol: 'Br'),
  'BZD': (name: 'Belize dollar', symbol: '\$'),
  'CAD': (name: 'Canadian dollar', symbol: '\$'),
  'CDF': (name: 'Congolese franc', symbol: 'FC'),
  'CHF': (name: 'Swiss franc', symbol: 'Fr'),
  'CKD': (name: 'Cook Islands dollar', symbol: '\$'),
  'CLP': (name: 'Chilean peso', symbol: '\$'),
  'CNY': (name: 'Chinese yuan', symbol: '¥'),
  'COP': (name: 'Colombian peso', symbol: '\$'),
  'CRC': (name: 'Costa Rican colón', symbol: '₡'),
  'CUC': (name: 'Cuban convertible peso', symbol: '\$'),
  'CUP': (name: 'Cuban peso', symbol: '\$'),
  'CVE': (name: 'Cape Verdean escudo', symbol: 'Esc'),
  'CZK': (name: 'Czech koruna', symbol: 'Kč'),
  'DJF': (name: 'Djiboutian franc', symbol: 'Fr'),
  'DKK': (name: 'Danish krone', symbol: 'kr'),
  'DOP': (name: 'Dominican peso', symbol: '\$'),
  'DZD': (name: 'Algerian dinar', symbol: 'دج'),
  'EGP': (name: 'Egyptian pound', symbol: '£'),
  'ERN': (name: 'Eritrean nakfa', symbol: 'Nfk'),
  'ETB': (name: 'Ethiopian birr', symbol: 'Br'),
  'EUR': (name: 'euro', symbol: '€'),
  'FJD': (name: 'Fijian dollar', symbol: '\$'),
  'FKP': (name: 'Falkland Islands pound', symbol: '£'),
  'FOK': (name: 'Faroese króna', symbol: 'kr'),
  'GBP': (name: 'British pound', symbol: '£'),
  'GEL': (name: 'lari', symbol: '₾'),
  'GGP': (name: 'Guernsey pound', symbol: '£'),
  'GHS': (name: 'Ghanaian cedi', symbol: '₵'),
  'GIP': (name: 'Gibraltar pound', symbol: '£'),
  'GMD': (name: 'dalasi', symbol: 'D'),
  'GNF': (name: 'Guinean franc', symbol: 'Fr'),
  'GTQ': (name: 'Guatemalan quetzal', symbol: 'Q'),
  'GYD': (name: 'Guyanese dollar', symbol: '\$'),
  'HKD': (name: 'Hong Kong dollar', symbol: '\$'),
  'HNL': (name: 'Honduran lempira', symbol: 'L'),
  'HTG': (name: 'Haitian gourde', symbol: 'G'),
  'HUF': (name: 'Hungarian forint', symbol: 'Ft'),
  'IDR': (name: 'Indonesian rupiah', symbol: 'Rp'),
  'ILS': (name: 'Israeli new shekel', symbol: '₪'),
  'IMP': (name: 'Manx pound', symbol: '£'),
  'INR': (name: 'Indian rupee', symbol: '₹'),
  'IQD': (name: 'Iraqi dinar', symbol: 'ع.د'),
  'IRR': (name: 'Iranian rial', symbol: '﷼'),
  'ISK': (name: 'Icelandic króna', symbol: 'kr'),
  'JEP': (name: 'Jersey pound', symbol: '£'),
  'JMD': (name: 'Jamaican dollar', symbol: '\$'),
  'JOD': (name: 'Jordanian dinar', symbol: 'د.ا'),
  'JPY': (name: 'Japanese yen', symbol: '¥'),
  'KES': (name: 'Kenyan shilling', symbol: 'Sh'),
  'KGS': (name: 'Kyrgyzstani som', symbol: 'с'),
  'KHR': (name: 'Cambodian riel', symbol: '៛'),
  'KID': (name: 'Kiribati dollar', symbol: '\$'),
  'KMF': (name: 'Comorian franc', symbol: 'Fr'),
  'KPW': (name: 'North Korean won', symbol: '₩'),
  'KRW': (name: 'South Korean won', symbol: '₩'),
  'KWD': (name: 'Kuwaiti dinar', symbol: 'د.ك'),
  'KYD': (name: 'Cayman Islands dollar', symbol: '\$'),
  'KZT': (name: 'Kazakhstani tenge', symbol: '₸'),
  'LAK': (name: 'Lao kip', symbol: '₭'),
  'LBP': (name: 'Lebanese pound', symbol: 'ل.ل'),
  'LKR': (name: 'Sri Lankan rupee', symbol: 'Rs  රු'),
  'LRD': (name: 'Liberian dollar', symbol: '\$'),
  'LSL': (name: 'Lesotho loti', symbol: 'L'),
  'LYD': (name: 'Libyan dinar', symbol: 'ل.د'),
  'MAD': (name: 'Moroccan dirham', symbol: 'DH'),
  'MDL': (name: 'Moldovan leu', symbol: 'L'),
  'MGA': (name: 'Malagasy ariary', symbol: 'Ar'),
  'MKD': (name: 'denar', symbol: 'den'),
  'MMK': (name: 'Burmese kyat', symbol: 'Ks'),
  'MNT': (name: 'Mongolian tögrög', symbol: '₮'),
  'MOP': (name: 'Macanese pataca', symbol: 'P'),
  'MRU': (name: 'Mauritanian ouguiya', symbol: 'UM'),
  'MUR': (name: 'Mauritian rupee', symbol: '₨'),
  'MVR': (name: 'Maldivian rufiyaa', symbol: '.ރ'),
  'MWK': (name: 'Malawian kwacha', symbol: 'MK'),
  'MXN': (name: 'Mexican peso', symbol: '\$'),
  'MYR': (name: 'Malaysian ringgit', symbol: 'RM'),
  'MZN': (name: 'Mozambican metical', symbol: 'MT'),
  'NAD': (name: 'Namibian dollar', symbol: '\$'),
  'NGN': (name: 'Nigerian naira', symbol: '₦'),
  'NIO': (name: 'Nicaraguan córdoba', symbol: 'C\$'),
  'NOK': (name: 'krone', symbol: 'kr'),
  'NPR': (name: 'Nepalese rupee', symbol: '₨'),
  'NZD': (name: 'New Zealand dollar', symbol: '\$'),
  'OMR': (name: 'Omani rial', symbol: 'ر.ع.'),
  'PAB': (name: 'Panamanian balboa', symbol: 'B/.'),
  'PEN': (name: 'Peruvian sol', symbol: 'S/ '),
  'PGK': (name: 'Papua New Guinean kina', symbol: 'K'),
  'PHP': (name: 'Philippine peso', symbol: '₱'),
  'PKR': (name: 'Pakistani rupee', symbol: '₨'),
  'PLN': (name: 'Polish złoty', symbol: 'zł'),
  'PYG': (name: 'Paraguayan guaraní', symbol: '₲'),
  'QAR': (name: 'Qatari riyal', symbol: 'ر.ق'),
  'RON': (name: 'Romanian leu', symbol: 'lei'),
  'RSD': (name: 'Serbian dinar', symbol: 'дин.'),
  'RUB': (name: 'Russian ruble', symbol: '₽'),
  'RWF': (name: 'Rwandan franc', symbol: 'Fr'),
  'SAR': (name: 'Saudi riyal', symbol: 'ر.س'),
  'SBD': (name: 'Solomon Islands dollar', symbol: '\$'),
  'SCR': (name: 'Seychellois rupee', symbol: '₨'),
  'SDG': (name: 'Sudanese pound', symbol: 'ج.س'),
  'SEK': (name: 'Swedish krona', symbol: 'kr'),
  'SGD': (name: 'Singapore dollar', symbol: '\$'),
  'SHP': (name: 'Saint Helena pound', symbol: '£'),
  'SLE': (name: 'Leone', symbol: 'Le'),
  'SOS': (name: 'Somali shilling', symbol: 'Sh'),
  'SRD': (name: 'Surinamese dollar', symbol: '\$'),
  'SSP': (name: 'South Sudanese pound', symbol: '£'),
  'STN': (name: 'São Tomé and Príncipe dobra', symbol: 'Db'),
  'SYP': (name: 'Syrian pound', symbol: '£'),
  'SZL': (name: 'Swazi lilangeni', symbol: 'L'),
  'THB': (name: 'Thai baht', symbol: '฿'),
  'TJS': (name: 'Tajikistani somoni', symbol: 'ЅМ'),
  'TMT': (name: 'Turkmenistan manat', symbol: 'm'),
  'TND': (name: 'Tunisian dinar', symbol: 'د.ت'),
  'TOP': (name: 'Tongan paʻanga', symbol: 'T\$'),
  'TRY': (name: 'Turkish lira', symbol: '₺'),
  'TTD': (name: 'Trinidad and Tobago dollar', symbol: '\$'),
  'TVD': (name: 'Tuvaluan dollar', symbol: '\$'),
  'TWD': (name: 'New Taiwan dollar', symbol: '\$'),
  'TZS': (name: 'Tanzanian shilling', symbol: 'Sh'),
  'UAH': (name: 'Ukrainian hryvnia', symbol: '₴'),
  'UGX': (name: 'Ugandan shilling', symbol: 'Sh'),
  'USD': (name: 'United States dollar', symbol: '\$'),
  'UYU': (name: 'Uruguayan peso', symbol: '\$'),
  'UZS': (name: 'Uzbekistani soʻm', symbol: 'so\'m'),
  'VES': (name: 'Venezuelan bolívar soberano', symbol: 'Bs.S.'),
  'VND': (name: 'Vietnamese đồng', symbol: '₫'),
  'VUV': (name: 'Vanuatu vatu', symbol: 'Vt'),
  'WST': (name: 'Samoan tālā', symbol: 'T'),
  'XAF': (name: 'Central African CFA franc', symbol: 'Fr'),
  'XCD': (name: 'Eastern Caribbean dollar', symbol: '\$'),
  'XOF': (name: 'West African CFA franc', symbol: 'Fr'),
  'XPF': (name: 'CFP franc', symbol: '₣'),
  'YER': (name: 'Yemeni rial', symbol: '﷼'),
  'ZAR': (name: 'South African rand', symbol: 'R'),
  'ZMW': (name: 'Zambian kwacha', symbol: 'ZK'),
  'ZWL': (name: 'Zimbabwean dollar', symbol: '\$'),
};
